name: pluggyTesty
version: '${project.version}'
main: co.tantleffbeef.pluggytesty.PluggyTesty
api-version: 1.19

depend: ["MCPlanes"]

commands:
  summonjawn:
    description: summons jawn
  summonseaman:
    description: summons seaman
  giveheavyarmor:
    description: give you heavy armor!!
  summongru:
    description: summons gru
  summonbouncer:
    description: summons gavvys special surprise
  chesttest:
    description: sets the loot table of a chest you are looking at
  bosstrial1:
    description: summons the Necromancer, the boss of trial 1
  bosstrial2:
    description: summons the Necromancer, the boss of trial 1
  bosstrial3:
    description: summons the Necromancer, the boss of trial 1
  bosstrial4:
    description: summons the Necromancer, the boss of trial 1
  bosstrial5:
    description: summons the Necromancer, the boss of trial 1
