name: pluggyTesty
version: '${project.version}'
main: co.tantleffbeef.pluggytesty.PluggyTesty
api-version: 1.19

depend: ["MCPlanes"]

commands:
  givemerod:
    description: gives you bolt rod
  givemepole:
    description: gives you frost pole
  givemesword:
    description: gives you a thick blade you can whack people with
  givemeheal:
    description: healing item cool
  givemesummon:
    description: summon summons
  givemed:
    description: suck my balls
  givemego:
    description: make you go
  givemecock:
    description: grngage launchger
  summonjawn:
    description: summons jawn
  summonseaman:
    description: summons seaman
  giveheavyarmor:
    description: give you heavy armor!!
  summongru:
    description: summons gru
  summonbouncer:
    description: summons gavvys special surprise
  givemedash:
    description: Dashes on Right-Click (4 Second Cooldown)
  givemeBow:
    description: Random Negative Effect Bow