name: pluggyTesty
version: '${project.version}'
main: co.tantleffbeef.pluggytesty.PluggyTesty
api-version: 1.20

depend: ["MCPlanes", "FastAsyncWorldEdit"]

commands:
  testexpedition:
    description: does some test expedition stuff
    aliases: ["te"]
  randomtestexpedition:
    description: test random expedition
    aliases: ["rte"]
  summonjawn:
    description: summons jawn
  summonseaman:
    description: summons seaman
  giveheavyarmor:
    description: give you heavy armor!!
  summongru:
    description: summons gru
  summonbouncer:
    description: summons gavvys special surprise
  chesttest:
    description: sets the loot table of a chest you are looking at
  trial1boss:
    description: summons the Necromancer, the boss of trial 1
  trial2boss:
    description: summons the Necromancer, the boss of trial 1
  trial3boss:
    description: summons the Necromancer, the boss of trial 1
  trial4boss:
    description: summons the Necromancer, the boss of trial 1
  trial5boss:
    description: summons the Necromancer, the boss of trial 1
  selectioninfo:
    description: bruh
    aliases: ["si"]
  leaveexpedition:
    description: removes you from being on whatever expedition
    aliases: ["le"]
