name: pluggyTesty
version: '${project.version}'
main: co.tantleffbeef.pluggytesty.PluggyTesty
api-version: 1.19

depend: ["MCPlanes"]

commands:
  givemed:
    description: suck my balls
  summonjawn:
    description: summons jawn
  summonseaman:
    description: summons seaman
  giveheavyarmor:
    description: give you heavy armor!!
  summongru:
    description: summons gru
  summonbouncer:
    description: summons gavvys special surprise