name: pluggyTesty
version: '${project.version}'
main: co.tantleffbeef.pluggytesty.PluggyTesty
api-version: 1.19

commands:
  givemewood:
    description: gives you would (but this would is magic and explosive and boom boom)
  givemerod:
    description: gives you bolt rod
  givemepole:
    description: gives you frost pole
  givemeheal:
    description: healing item cool
  givemesummon:
    description: summon summons
  dontgivemeWE:
    description: suck my balls
  givemego:
    description: make you go
